name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag soorajcalicut/ubuntu:$(date +%s)
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.D_HUB_USER }}
        password: ${{ secrets.D_HUB_PWD }}
        repository: soorajcalicut/ubuntu
        tag_with_ref: true
